// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC45jy2owQer29NE7yFGDaDqOKYinUgkZc',
    appId: '1:556642308142:web:b5820f71de80a55bd58fbf',
    messagingSenderId: '556642308142',
    projectId: 'fir-tutorial-72b4c',
    authDomain: 'fir-tutorial-72b4c.firebaseapp.com',
    storageBucket: 'fir-tutorial-72b4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVP7EsW_dqEP23DOvdD3bbfljaqqbXzTs',
    appId: '1:556642308142:android:c88263ad2b5a6ff2d58fbf',
    messagingSenderId: '556642308142',
    projectId: 'fir-tutorial-72b4c',
    storageBucket: 'fir-tutorial-72b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtry6jKKcfUcg9yU7HEQRLNOR6NEyT3XY',
    appId: '1:556642308142:ios:922e4bbe0aef91f5d58fbf',
    messagingSenderId: '556642308142',
    projectId: 'fir-tutorial-72b4c',
    storageBucket: 'fir-tutorial-72b4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtry6jKKcfUcg9yU7HEQRLNOR6NEyT3XY',
    appId: '1:556642308142:ios:922e4bbe0aef91f5d58fbf',
    messagingSenderId: '556642308142',
    projectId: 'fir-tutorial-72b4c',
    storageBucket: 'fir-tutorial-72b4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC45jy2owQer29NE7yFGDaDqOKYinUgkZc',
    appId: '1:556642308142:web:641a1d770b28c1cfd58fbf',
    messagingSenderId: '556642308142',
    projectId: 'fir-tutorial-72b4c',
    authDomain: 'fir-tutorial-72b4c.firebaseapp.com',
    storageBucket: 'fir-tutorial-72b4c.firebasestorage.app',
  );
}
